# Generated by Django 3.1.2 on 2020-10-23 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='rbox.department')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('created', models.DateField()),
                ('notes', models.CharField(max_length=100)),
                ('taste_score', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')], null=True)),
                ('effort_score', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')], null=True)),
                ('active_minutes', models.PositiveSmallIntegerField(default=0)),
                ('total_minutes', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(to='rbox.Category')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_order', models.SmallIntegerField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5)),
                ('quantity_unit', models.CharField(blank=True, default='', max_length=25)),
                ('prep_notes', models.CharField(blank=True, max_length=200)),
                ('containing_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbox.recipe')),
                ('ingredient', models.ForeignKey(default='---', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rbox.ingredient')),
            ],
        ),
    ]
