# Generated by Django 3.1.2 on 2020-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbox', '0002_auto_20201023_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(to='rbox.Category'),
        ),
    ]
