# Generated by Django 3.1.2 on 2020-10-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbox', '0003_auto_20201023_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='effort_score',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')], default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='taste_score',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')], default=0),
        ),
    ]
