# Generated by Django 3.1.2 on 2020-10-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbox', '0004_auto_20201023_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
