# Generated by Django 3.1.2 on 2020-10-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbox', '0005_auto_20201023_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='effort_score',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Very Hard'), (2, 'Hard'), (3, 'Moderate'), (4, 'Easy'), (5, 'Very Easy')], default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
