# Generated by Django 3.1.2 on 2020-10-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbox', '0007_auto_20201023_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
