# Generated by Django 3.1.2 on 2020-11-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbox', '0008_auto_20201024_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientline',
            name='prep_notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
